/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package extraordinario;
import java.awt.Color;
 import java.awt.event.ItemEvent;
import java.awt.event.ItemListener; 
import javax.swing.JOptionPane; 
public class Resistencia1 extends javax.swing.JFrame {

    /**
     * Creates new form Resistencia1
     */
    
    public Resistencia1() {
        initComponents();
        this.setLocationRelativeTo(null );
        this.setTitle("Resistencia1");
        this.getContentPane().setBackground(getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbBanda1 = new javax.swing.JComboBox<>();
        cmbBanda2 = new javax.swing.JComboBox<>();
        cmbBanda3 = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cbTolerancia = new javax.swing.JCheckBox();
        cbTolerancia2 = new javax.swing.JCheckBox();
        cbTolerancia3 = new javax.swing.JCheckBox();
        btnBanda1 = new javax.swing.JButton();
        btnBanda2 = new javax.swing.JButton();
        btnBanda3 = new javax.swing.JButton();
        btnBanda4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 3, 24)); // NOI18N
        jLabel1.setText("Calcular Resistencias ");

        cmbBanda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Cafe", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cmbBanda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBanda1MouseClicked(evt);
            }
        });
        cmbBanda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBanda1ActionPerformed(evt);
            }
        });

        cmbBanda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Cafe", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cmbBanda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBanda2ActionPerformed(evt);
            }
        });

        cmbBanda3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Cafe", "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Violeta", "Gris", "Blanco" }));
        cmbBanda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBanda3ActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbTolerancia);
        cbTolerancia.setText("Rojo");
        cbTolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToleranciaActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbTolerancia2);
        cbTolerancia2.setText("Dorado");
        cbTolerancia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTolerancia2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbTolerancia3);
        cbTolerancia3.setText("plata");
        cbTolerancia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTolerancia3ActionPerformed(evt);
            }
        });

        btnBanda1.setText(" ");
        btnBanda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanda1ActionPerformed(evt);
            }
        });

        btnBanda2.setText(" ");

        btnBanda3.setText("jButton2");

        btnBanda4.setText("jButton3");

        jLabel2.setText("_______________________________________________________");

        jLabel3.setText("_______________________________________________________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cmbBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))
                                            .addComponent(cmbBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(cmbBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbTolerancia)
                                                    .addComponent(cbTolerancia3)
                                                    .addComponent(cbTolerancia2)
                                                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(btnBanda4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(cbTolerancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTolerancia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTolerancia3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBanda1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanda2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanda3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanda4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addGap(89, 89, 89)
                .addComponent(btnRegresar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 850, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanda1ActionPerformed

    private void cbTolerancia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTolerancia3ActionPerformed
        // TODO add your handling code here:
        tolerancia =10;
        btnBanda4.setBackground(Color.DARK_GRAY );
    }//GEN-LAST:event_cbTolerancia3ActionPerformed

    private void cbTolerancia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTolerancia2ActionPerformed
        // TODO add your handling code here:
        tolerancia = 5;
         btnBanda4.setBackground(Color.yellow);
    }//GEN-LAST:event_cbTolerancia2ActionPerformed

    private void cbToleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToleranciaActionPerformed
        tolerancia=2;
         btnBanda4.setBackground(Color.red);
    }//GEN-LAST:event_cbToleranciaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      Main form = new Main();
          form.setVisible(true);
          this.dispose(); 
         
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        resultado = (valor1+=valor2); 
        JOptionPane.showMessageDialog(null, "El valor de la aresistencia es "+ resultado *valor3 +"Ohms"+"\n"+ "con una tolerancia de : "+tolerancia +"%");

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbBanda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBanda3ActionPerformed
        valor3=0;
        int x;
        x= cmbBanda3.getSelectedIndex() ;
        switch(x){
            case 0: // negro
            valor3 =1 ;
             btnBanda3.setBackground(Color.black);  
            break;
            case 1: // cafe
            valor3 =1;
            btnBanda3.setBackground(Color.darkGray);
            break;
            case 2:   //"rojo":
            valor3 =10;
            btnBanda3.setBackground(Color.red);
            break;
            case 3://naranja
            valor3 =100;
            btnBanda3.setBackground(Color.orange);
            break;
            case 4: //amarillo
            valor3 =1000;
            btnBanda3.setBackground(Color.yellow);
            break;
            case 5: //verde
            valor3 =10000;
            btnBanda3.setBackground(Color.green);
            break;
            case 6://azul
            valor3 =100000;
            btnBanda3.setBackground(Color.blue);
            break;
            case 7: //violeta
            valor3 =1000000;
            btnBanda3.setBackground(Color.MAGENTA );
            break;
            case 8: //gris
            valor3 =10000000;
            btnBanda3.setBackground(Color.DARK_GRAY );
            break;
            case 9: //blanco
            valor3 =100000000;
             btnBanda3.setBackground(Color.white);
            break;
        }
        
    }//GEN-LAST:event_cmbBanda3ActionPerformed

    private void cmbBanda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBanda2ActionPerformed
        valor2=0;
        valor2= cmbBanda2.getSelectedIndex() ; 
        switch( valor2){
            case 0: // negro
            btnBanda2.setBackground(Color.black);  
            break;
            case 1: // cafe
             btnBanda2.setBackground(Color.darkGray);
            break;
            case 2:   //"rojo":
             btnBanda2.setBackground(Color.red);
            break;
            case 3://naranja
            btnBanda2.setBackground(Color.orange);
            break;
            case 4: //amarillo
            btnBanda2.setBackground(Color.yellow);
            break;
            case 5: //verde
            btnBanda2.setBackground(Color.green);
            break;
            case 6://azul
           btnBanda2.setBackground(Color.blue);
            break;
            case 7: //violeta
            btnBanda2.setBackground(Color.MAGENTA );
            break;
            case 8: //gris
            btnBanda2.setBackground(Color.DARK_GRAY );
            break;
            case 9: //blanco
             btnBanda2.setBackground(Color.white);
            break;
        }
    }//GEN-LAST:event_cmbBanda2ActionPerformed

    private void cmbBanda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBanda1ActionPerformed
        valor1=0;
        valor1= cmbBanda1.getSelectedIndex()*10; 
        switch( valor1){
            case 0: // negro
            btnBanda1.setBackground(Color.black);  
            break;
            case 10: // cafe
             btnBanda1.setBackground(Color.darkGray);
            break;
            case 20:   //"rojo":
             btnBanda1.setBackground(Color.red);
            break;
            case 30://naranja
            btnBanda1.setBackground(Color.orange);
            break;
            case 40: //amarillo
            btnBanda1.setBackground(Color.yellow);
            break;
            case 50: //verde
            btnBanda1.setBackground(Color.green);
            break;
            case 60://azul
           btnBanda1.setBackground(Color.blue);
            break;
            case 70: //violeta
            btnBanda1.setBackground(Color.MAGENTA );
            break;
            case 80: //gris
            btnBanda1.setBackground(Color.DARK_GRAY );
            break;
            case 90: //blanco
             btnBanda1.setBackground(Color.white);
            break;
        } 
    }//GEN-LAST:event_cmbBanda1ActionPerformed

    private void cmbBanda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBanda1MouseClicked

    }//GEN-LAST:event_cmbBanda1MouseClicked

 
    int valor1 ,valor2 ,valor3   ,resultado ,tolerancia ;
    //int x,y,z;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resistencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resistencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resistencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resistencia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resistencia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanda1;
    private javax.swing.JButton btnBanda2;
    private javax.swing.JButton btnBanda3;
    private javax.swing.JButton btnBanda4;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbTolerancia;
    private javax.swing.JCheckBox cbTolerancia2;
    private javax.swing.JCheckBox cbTolerancia3;
    private javax.swing.JComboBox<String> cmbBanda1;
    private javax.swing.JComboBox<String> cmbBanda2;
    private javax.swing.JComboBox<String> cmbBanda3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
